### ISSUE TITLE
🐣 [FEATURE] Main page-포트폴리오, 팀 활동

### ISSUE THREAD

**Issue by chloenam** [Doong-Ji/doong-ji.github.io#2]
#  Main page-포트폴리오, 팀 활동

-  포트폴리오, 팀 활동 섹션 구성

## 완료 조건 ✅

- [x] 포트폴리오 html
- [x] 팀 활동 html
- [x] 포트폴리오 css
- [x] 팀 활동 css

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by EUN-HYE-KIM** [comment]
팀 활동 cssbox에 적용된
